# TUGAS MINGGU KELIMA (MATA KULIAH ALGORITMA DAN STRUKTUR DATA)

# 5.16 LIST 2 DIMENSI
List 2 dimensi pada umumnya adalah menempatkan sebuah list di dalam list. Penggambarannya seperti sebuah matrik.

Berikut contoh latihan List 2 Dimensi:

In [1]:
#latihan List 2 Dimensi (1)

#pertama-tama pikirkan dan buat list yang diinginkan
#dalam setiap list, urutannya masih sama pada materi list sebelumnya
#yaitu dari kiri urutannya mulai dari 0, 1, 2, dan seterusnya, dan dari kanan urutannya mulai dari -1, -2, -3 dan seterusnya
matrik = [ 
    [11,12,13,14], 
    [15,16,17,18],
    [19,20,21,22],
    [23,24,25,26]
]
#mencetak semua list yang ada dalam list
print(matrik)

[[11, 12, 13, 14], [15, 16, 17, 18], [19, 20, 21, 22], [23, 24, 25, 26]]


In [2]:
#latihan List 2 Dimensi (2)

#list yang digunakan masih sama dengan latihan 1

#list urutan ke 0 atau -4 adalah list [11,12,13,14]
#dimana dalam list tersebut 11 = urutan ke 0 atau -4, 12 = urutan ke 1 atau -3, 13 = urutan ke 2 atau -2, dan 14 = urutan ke 3 atau -1

#list urutan ke 1 atau -3 adalah list [15,16,17,18]
#dimana dalam list tersebut 15 = urutan ke 0 atau -4, 16 = urutan ke 1 atau -3, 17 = urutan ke 2 atau -2, dan 18 = urutan ke 3 atau -1

#list urutan ke 2 atau -2 adalah list [19,20,21,22]
#dimana dalam list tersebut 19 = urutan ke 0 atau -4, 20 = urutan ke 1 atau -3, 21 = urutan ke 2 atau -2, dan 22 = urutan ke 3 atau -1

#list urutan ke 3 atau -1 adalah list [23,24,25,26]
#dimana dalam list tersebut 23 = urutan ke 0 atau -4, 24 = urutan ke 1 atau -3, 25 = urutan ke 2 atau -2, dan 26 = urutan ke 3 atau -1

#sehingga ketika kita ingin mencetak list pada urutan ke -2 yaitu dengan aturan:
matrik[-2]

[19, 20, 21, 22]

In [3]:
#latihan List 2 Dimensi (3)

#list yang digunakan masih sama dengan latihan 1
#untuk penjelasan urutannya juga sama dengan latihan 2

#ketika kita ingin mencetak list pada urutan ke 3, yang dimana list tersebut berada dalam list urutan ke -2, yaitu dengan menggunakan aturan:
matrik[-2][3]

22

In [5]:
#latihan List 2 Dimensi (4)

#list yang digunakan masih sama dengan latihan 1
#untuk penjelasan urutannya juga sama dengan latihan 2

#ketika kita ingin mengubah dan mencetak list pada urutan ke 3, yang dimana list tersebut berada dalam list urutan ke -2, yaitu dengan aturan:
#misalkan ingin mengubah 22 menjadi 50
matrik[-2][3] = 50
print(matrik[-2][3])

50


In [6]:
#latihan List 2 Dimensi (5)

#list yang digunakan masih sama dengan latihan 1
#untuk penjelasan urutannya masih sama dengan latihan 2
#hanya saja dalam list pada urutan ke 3, yang dimana list tersebut berada dalam list urutan ke -2 sudah diubah menjadi 50

#sehingga jika kita mencetak ulang semua list akan seperti berikut ini:
matrik

[[11, 12, 13, 14], [15, 16, 17, 18], [19, 20, 21, 50], [23, 24, 25, 26]]

In [7]:
#latihan List 2 Dimensi (6)

#dari latihan 5, kita sudah mencetak list baru
#sehingga ketika kita ingin memanggil anggota dari list tersebut yaitu dengan aturan:
for baris in matrik:
    print(baris)
    for kolom in baris:
        print(kolom)

[11, 12, 13, 14]
11
12
13
14
[15, 16, 17, 18]
15
16
17
18
[19, 20, 21, 50]
19
20
21
50
[23, 24, 25, 26]
23
24
25
26


# 5.17 TUPLES
Tuples mirip dengan list, akan tetapi tuples tidak dapat dirubah isinya. Jika kita memiliki data yang tidak ingin dirubah isinya, kita gunakan tuples, sedangkan jika datanya masih ingin dimanipulasi kedepannya, gunakan list.

Berikut contoh latihan Tuples:

In [1]:
#latihan Tuples (1)

#pertama-tama pikirkan dan buat data yang diinginkan
angka = (3,4,5,5,6,7)

#dalam tuples, urutan dalam datanya masih sama seperti list
#3 = urutan ke 0 atau -6
#4 = urutan ke 1 atau -5
#5 (sebelah kiri) = urutan ke 2 atau -4
#5 (sebelah kanan) = urutan ke 3 atau -3
#6 = urutan ke 4 atau -2
#7 = urutan ke 5 atau -1

#ketika kita ingin mencetak data ke 3 dalam tumples, yaitu menggunakan cara sebagai berikut:
print(angka[3])

5


In [2]:
#latihan Tuples (2)

#data yang digunakan masih sama dengan latihan 1
#untuk penjelasan urutannya juga sama pada latihan 1

#cara mencetak data dari urutan ke -5 dengan batas sebelum -1, yaitu sebagai berikut:
print(angka[-5:-1])

(4, 5, 5, 6)


In [3]:
#latihan Tuples (3)

#data yang digunakan masih sama dengan latihan 1
#untuk penjelasan urutannya juga sama pada latihan 1 

#cara untuk memanggil semua anggota data dari urutan ke -5 dengan batas sebelum -1, yaitu sebagai berikut:
for isi in angka[-5:-1]:
    print(isi)

4
5
5
6


In [4]:
#latihan Tuples (4)

angka[2] = 50
#karena Tuples tidak dapat dirubah datanya, maka outputnya tidak muncul (error)

TypeError: 'tuple' object does not support item assignment

In [5]:
#latihan Tuples (5)

angka.append(2)
#karena Tuples tidak dapat dirubah datanya, maka outputnya tidak muncul (error)

AttributeError: 'tuple' object has no attribute 'append'

In [6]:
#latihan Tuples (6)

angka.remove(4)
#karena Tuples tidak dapat dirubah datanya, maka outputnya tidak muncul (error)

AttributeError: 'tuple' object has no attribute 'remove'

In [7]:
#latihan Tuples (7)

#data yang digunakan masih sama dengan latihan 1
#untuk penjelasan urutannya juga sama pada latihan 1 (langkah manual)

#cara untuk mengetahui dan memastikan anggota data "7" pada urutan keberapa, yaitu sebagai berikut:
angka.index(7)

#hasil output sama dengan langkah manual

5

In [8]:
#latihan Tuples (8)

#data yang digunakan masih sama dengan latihan 1
#untuk penjelasan urutannya juga sama pada latihan 1 (langkah manual)

#cara untuk mengetahui dan memastikan anggota data "4" pada urutan keberapa, yaitu sebagai berikut:
angka.index(4)

#hasil output sama dengan langkah manual

1

In [9]:
#latihan Tuples (9)

#data yang digunakan masih sama dengan latihan 1
#untuk penjelasan urutannya juga sama pada latihan 1

#cara untuk mengetahui anggota data "5" ada berapa, yaitu sebagai berikut:
angka.count(5)

#karena anggota "5" dalam data ada 2, maka hasil output nya adalah 2

2

In [10]:
#latihan Tuples (10)

#data yang digunakan masih sama dengan latihan 1
#untuk penjelasan urutannya juga sama pada latihan 1

#cara untuk mengetahui anggota data "3" ada berapa, yaitu sebagai berikut:
angka.count(3)

#karena anggota "3" dalam data ada 1, maka hasil output nya adalah 2

1

# 5.18 DICTIONARIES
Dictionaries digunakan jika data nya terkait satu sama lain. Misalnya data seseorang yang terdiri dari umur, nama, tanggal lahir merupakan satu kesatuan data yang bersumber dari orang tersebut.

Berikut contoh latihan Dictionaries:

In [37]:
#latihan dictionaries (1)

#pertama_tama buat data yang ingin dijalankan
data_orang = {
    "Nama" : "Wulanda Asmara",
    "Umur" : 19,
    "Seorang_mahasiswa" : True
}

#mencetak data yang sudah dibuat
print(data_orang)

{'Nama': 'Wulanda Asmara', 'Umur': 19, 'Seorang_mahasiswa': True}


In [38]:
#latihan dictionaries (2)

#mencetak data nama berdasarkan data yang sudah dibuat
print(data_orang["Nama"])

Wulanda Asmara


In [40]:
#latihan dictionaries (3)

#mencetak data nama berdasarkan data yang sudah dibuat
print(data_orang["nama"])
#karena dalam data ditulis "Nama" bukan "nama" sehingga outputnya error

KeyError: 'nama'

In [41]:
#latihan dictionaries (4)

#mencetak data nama berdasarkan data yang sudah dibuat
print(data_orang.get("Nama"))

Wulanda Asmara


In [39]:
#latihan dictionaries (5)

#mencetak data nama berdasarkan data yang sudah dibuat
print(data_orang.get("nama"))
#karena dalam data ditulis "Nama" bukan "nama" sehingga outputnya "none (tidak ada)"

None


In [43]:
#latihan dictionaries (6)

#menambahkan dan mencetak data tanggal lahir yang diinginkan
print(data_orang.get("Tanggal_lahir", "7-11-2003"))

7-11-2003


In [45]:
#latihan dictionaries (7)

#menambahkan dan mencetak data no HP yang diinginkan
data_orang["HP"] = "082147380230"
print(data_orang["HP"])

082147380230


In [46]:
#membuat data program yang ingin dijalankan
angka = {
    "0" : "nol",
    "1" : "satu",
    "2" : "dua",
    "3" : "tiga",
    "4" : "empat",
    "5" : "lima",
    "6" : "enam",
    "7" : "tujuh",
    "8" : "delapan",
    "9" : "sembilan",
}

In [47]:
#latihan dictionaries (8)

#berikut latihan untuk merubah angka menjadi sebutan bilangan tersebut

#mengimput data berupa angka
NIM = input("Masukkan NIM Anda : ")
nomor_angka = ""
for isi in NIM:
    nomor_angka += angka.get(isi) + " "
    
#mencetak data berupa sebutan bilangan
print(nomor_angka)

Masukkan NIM Anda : 2208541017
dua dua nol delapan lima empat satu nol satu tujuh 


# 5.19 FUNGSI DALAM PYTHON
Tanpa disadari kita telah menerapkan beberapa jenis fungsi pada Python seperti fungsi input, print, len, range, dll. Pada dasarnya fungsi dibentuk untuk menghidari pengulangan pembuatan program secara manual dimana fungsi tersebut memiliki pengulangan yang tinggi dalam program yang kita buat. Jadi untuk mempermudah dan meringkas program yang kita buat, setiap fungsi tersebut dibutuhkan tinggal kita panggil.

Berikut contoh latihan Fungsi dalam Python:

In [35]:
#membuat program yang ingin dijalankan
def full_nama(first_name, last_name):
    print(f"Nama lengkapnya adalah {first_name} {last_name}")

In [36]:
#latihan 1

#menginput nama depan dan nama belakang yang diinginkan
first_name = input("Nama depan mu adalah : ")
last_name = input("Nama belakang mu adalah : ")

#menggabungkan nama depan dan nama belakang yang sudah diinput
full_nama(first_name,last_name)

Nama depan mu adalah : Wulanda
Nama belakang mu adalah : Asmara
Nama lengkapnya adalah Wulanda Asmara


# 5.19.1 Tugas Fungsi pada Python
Ada dua jenis tugas fungsi pada Python yaitu:
    - Menjalankan perintah.
    - Menampilkan hasil perhitungan.
    
Berikut contoh latihannya:

In [13]:
#membuat program yang ingin dijalankan
def waktu_sampai(jarak, kecepatan):
    waktu = jarak/kecepatan
    print(waktu)

In [14]:
#membuat program yang ingin dijalankan
def waktu_tempuh(jarak, kecepatan):
    waktu = jarak/kecepatan
    return waktu

In [16]:
#latihan 1

#menentukan waktu sampai sesuai definisi program yang sudah dibuat
waktu_sampai(90,45)

2.0


In [17]:
#latihan 2

#menentukan waktu sampai sesuai definisi program yang sudah dibuat
waktu_tempuh(90,45)

2.0

In [32]:
#latihan 3

#menentukan waktu sampai sesuai definisi program yang sudah dibuat
x = waktu_sampai(100,80)
print(x)

1.25
None


In [33]:
#latihan 4

#menentukan waktu sampai sesuai definisi program yang sudah dibuat
y = waktu_tempuh(100,80)
print(y)

1.25


In [23]:
#membuat program yang ingin dijalankan
def luas_segitiga(alas,tinggi):
    luas = (1/2)*alas*tinggi
    return luas

In [24]:
#latihan 5

#menentukan luas segitiga sesuai definisi program yang sudah dibuat
luas_segitiga(5,8)

20.0

In [27]:
#membuat program yang ingin dijalankan
def luas_persegi(sisi):
    luas = sisi**2
    return luas

In [28]:
#latihan 6

#menentukan luas persegi sesuai definisi program yang sudah dibuat
luas_persegi(14)

196

In [29]:
#latihan 7

#menginput jenis bidang yang diinginkan
jenis_bidang = input("Tulis jenis bidangnya : ")
if jenis_bidang.upper() == "SEGITIGA":
    alas = float(input("Tuliskan panjang alasnya : "))
    tinggi = float(input("Tuliskan tingginya : "))
    luas = luas_segitiga(alas,tinggi)
    print(f"Luas {jenis_bidang} adalah {luas}")
elif jenis_bidang.upper() == "PERSEGI":
    sisi = float(input("Tuliskan panjang sisinya : "))
    luas = luas_persegi(sisi)
    print(f"Luas {jenis_bidang} adalah {luas}")

#jika bidang yang diinput tidak ada dalam program yang dibuat, maka hasil output nya akan muncul seperti berikut:
else:
    print(f"Maaf bidang {jenis_bidang} yang kamu masukkan tidak terdaftar.")
    print("Hanya ada pilihan SEGITIGA DAN PERSEGI.")
    print("Terima kasih.")

Tulis jenis bidangnya : PERSEGI
Tuliskan panjang sisinya : 8
Luas PERSEGI adalah 64.0


In [30]:
#latihan 8

#menginput jenis bidang yang diinginkan
jenis_bidang = input("Tulis jenis bidangnya : ")
if jenis_bidang.upper() == "SEGITIGA":
    alas = float(input("Tuliskan panjang alasnya : "))
    tinggi = float(input("Tuliskan tingginya : "))
    luas = luas_segitiga(alas,tinggi)
    print(f"Luas {jenis_bidang} adalah {luas}")
elif jenis_bidang.upper() == "PERSEGI":
    sisi = float(input("Tuliskan panjang sisinya : "))
    luas = luas_persegi(sisi)
    print(f"Luas {jenis_bidang} adalah {luas}")
    
#jika bidang yang diinput tidak ada dalam program yang dibuat, maka hasil output nya akan muncul seperti berikut:
else:
    print(f"Maaf bidang {jenis_bidang} yang kamu masukkan tidak terdaftar.")
    print("Hanya ada pilihan SEGITIGA DAN PERSEGI.")
    print("Terima kasih.")

Tulis jenis bidangnya : LINGKARAN
Maaf bidang LINGKARAN yang kamu masukkan tidak terdaftar.
Hanya ada pilihan SEGITIGA DAN PERSEGI.
Terima kasih.


In [31]:
#latihan 9

#menginput jenis bidang yang diinginkan
jenis_bidang = input("Tulis jenis bidangnya : ")
if jenis_bidang.upper() == "SEGITIGA":
    alas = float(input("Tuliskan panjang alasnya : "))
    tinggi = float(input("Tuliskan tingginya : "))
    luas = luas_segitiga(alas,tinggi)
    print(f"Luas {jenis_bidang} adalah {luas}")
elif jenis_bidang.upper() == "PERSEGI":
    sisi = float(input("Tuliskan panjang sisinya : "))
    luas = luas_persegi(sisi)
    print(f"Luas {jenis_bidang} adalah {luas}")

#jika bidang yang diinput tidak ada dalam program yang dibuat, maka hasil output nya akan muncul seperti berikut:
else:
    print(f"Maaf bidang {jenis_bidang} yang kamu masukkan tidak terdaftar.")
    print("Hanya ada pilihan SEGITIGA DAN PERSEGI.")
    print("Terima kasih.")

Tulis jenis bidangnya : SEGITIGA
Tuliskan panjang alasnya : 10
Tuliskan tingginya : 15
Luas SEGITIGA adalah 75.0


# 5.20 NUMPY
Numpy merupakan salah satu Library dalam Python yang memiliki keunggulan dalam perhitungan menggunakan vektor dan matrik dalam berbagai dimensi. Hal pertama yang perlu dilakukan adalah memanggil Library Numpy sebagai berikut:

In [49]:
import numpy as np

Berikut latihan Numpy:

# 5.20.1 Perintah Dasar pada Numpy
Beberapa perintah dalam Numpy diantaranya memanggil Numpy, mengetahui dimensi dan ukuran variabel.

In [50]:
#latihan 1

#pertama-tama pikirkan dan buat Numpy yang diinginkan
x = np.array([6,7,8,9,10])

#cara memanggil anggota Numpy (x), sebagai berikut
print(x)

[ 6  7  8  9 10]


In [51]:
#latihan 2

#pertama-tama pikirkan dan buat Numpy yang berbeda dari latihan 1
y = np.array([[11,12,13], [14,15,16]])

#cara menggil anggota Numpy (y) , sebagi berikut:
print(y)

[[11 12 13]
 [14 15 16]]


In [52]:
#latihan 3

#pertama-tama pikirkan dan buat Numpy berbeda dari latihan 1 dan 2
z = ([[[17,18,19], [20,21,22]], 
      [[24,25,26], [27,28,29]],
      [[30,31,32], [33,34,35]]])

#cara memanggil anggota Numpy  (z), sebagai berikut:
print(z)

[[[17, 18, 19], [20, 21, 22]], [[24, 25, 26], [27, 28, 29]], [[30, 31, 32], [33, 34, 35]]]


In [8]:
#latihan 4

#cara untuk mengetahui dimensi dari Numpy pada latihan 1, sebagai berikut:
x.ndim

1

In [9]:
#latihan 5

#cara untuk mengetahui dimensi dari Numpy pada latihan 2, sebagai berikut:
y.ndim

2

In [10]:
#latihan 6

#cara untuk mengetahui dimensi dari Numpy pada latihan 3, sebagai berikut:
z.ndim
#mohon maaf pak, ini saya tidak tahu kenapa bisa error
#mungkin karena numpy yang dibuat terlalu besar, sehingga program tidak bisa dijalankan

AttributeError: 'list' object has no attribute 'ndim'

In [12]:
#latihan 7

#cara untuk mengetahui ukuran variabel dari Numpy pada latihan 1, sebagai berikut:
x.shape

#karena pada latihan 1 terdapat 5 anggota Numpy maka outputnya adalah (5,)

(5,)

In [13]:
#latihan 8

#cara untuk mengetahui ukuran variabel dari Numpy pada latihan 2, sebagai berikut:
y.shape

#pada latihan 2 terdapat 2 anggota Numpy, yang dimana tiap anggotanya memiliki 3 anggota lagi
#sehingga outputnya adalah (2,3)

(2, 3)

In [11]:
#latihan 9

#cara untuk mengetahui ukuran variabel dari Numpy pada latihan 3, sebagai berikut:
z.shape
#mohon maaf pak, ini saya tidak tahu kenapa bisa error
#mungkin karena numpy yang dibuat terlalu besar, sehingga program tidak bisa dijalankan

AttributeError: 'list' object has no attribute 'shape'

# 5.20.2 Memanggil Anggota, Kolom, dan Baris dengan Numpy

In [26]:
#latihan 1

#pertama-tama pikirkan dan buat Numpy yang diinginkan
a = np.array([[7,8,9,10,11], [12,13,14,15,16], [17,18,19,20,21]])

#andaikan seperti matrik
#[7,8,9,10,11] baris ke 0, 
#dimana 7 = kolom ke 0, 8 = kolom ke 1, dan 9 = kolom ke 2, 10 = kolom ke 3, 11 = kolom ke 4
#[12,13,14,15,16] baris ke 1
#dimana 12 = kolom ke 0, 13 = kolom ke 1, dan 14 = kolom ke 2, 15 = kolom ke 3, 16 = kolom ke 4
#[17,18,19,20,21] baris ke 2
#dimana 17 = kolom ke 0, 18 = kolom ke 1, dan 19 = kolom ke 2, 20 = kolom ke 3, 21 = kolom ke 4

#memanggil anggota Numpy (a)
print(a)

[[ 7  8  9 10 11]
 [12 13 14 15 16]
 [17 18 19 20 21]]


In [27]:
#latihan 2

#cara memanggil anggota pada baris ke 0 kolom ke 2
a[0,2]

9

In [28]:
#latihan 3

#cara memanggil semua anggota pada baris ke 1
a[1,:]

array([12, 13, 14, 15, 16])

In [29]:
#latihan 4

#cara memanggil semua anggota pada kolom ke 1
a[:,1]

array([ 8, 13, 18])

In [30]:
#latihan 5

#cara memanggil anggota pada baris ke 0, dari kolom ke 0 dengan batas sebelum kolom ke 2
a[0,0:2]

array([7, 8])

In [31]:
#latihan 6

#cara memanggil anggota pada baris ke 0, dari kolom ke 1 dengan batas sebelum kolom ke 4 dengan loncatan 2 kolom
a[0,1:4:2]

array([ 8, 10])

In [32]:
#latihan 7

#mengubah anggota pada baris ke 2 kolom ke 4 menjadi "50"
a[2,4] = 50
print(a)

[[ 7  8  9 10 11]
 [12 13 14 15 16]
 [17 18 19 20 50]]


# 5.20.3 Matrix pada Numpy

In [34]:
#latihan 1

#membuat matrik 1 dengan jumlah baris ada 2 dan jumlah kolom ada 3
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [35]:
#latihan 2

#membuat matrik 0 dengan jumlah baris ada 3 dan jumlah kolom ada 4
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [38]:
#latihan 3

#membuat matrik identitas dengan jumlah baris ada 3
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [39]:
#latihan 4

#membuat 3 matrik 1, dengan jumlah baris ada 4 dan jumlah kolom ada 5
np.ones((3,4,5))

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [41]:
#latihan 5

#membuat matrik 5, dengan jumlah baris ada 3 dan jumlah kolom ada 4
np.full((3,4),5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [44]:
#latihan 6

#membuat matrik random, dengan jumlah baris ada 3 dan jumlah kolom ada 5
np.random.rand(3,5)

array([[0.31120631, 0.42829275, 0.47382348, 0.66922182, 0.3307722 ],
       [0.01746261, 0.59155527, 0.52422754, 0.79588102, 0.09634125],
       [0.66908204, 0.70163857, 0.43314974, 0.40991528, 0.08378576]])

In [47]:
#latihan 7

#membuat matrik random bilangan antara 11 sampai 20 (bukan desimal), dengan jumlah baris ada 4 dan kolom ada 5
np.random.randint(11,20,size=(4,5))

array([[15, 11, 13, 19, 18],
       [14, 15, 16, 16, 15],
       [17, 12, 11, 11, 14],
       [17, 18, 11, 16, 11]])

In [53]:
#latihan 8

#membuat dan mencetak matrik 0 berordo 10x10
a = np.zeros((10,10))
print(a)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [54]:
#latihan 9

#membuat dan mencetak matrik identitas berordo 10x10
b = np.identity(10)
print(b)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


In [55]:
#latihan 10

#mengalikan dengan 9 dan mencetak matrik b pada latihan 9 
c = 9*b
print(c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 9. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 9. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 9. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 9. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 9. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 9. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


In [57]:
#latihan 11

#membuat matrik 1 berordo 8x8
d = np.ones((8,8))

#membuat matrik identitas berordo 8x8
e = np.identity(8)*8

#menjumlahkan dan mencetak matrik (d) dan matrik (e)
f = d+e
print(f)

[[9. 1. 1. 1. 1. 1. 1. 1.]
 [1. 9. 1. 1. 1. 1. 1. 1.]
 [1. 1. 9. 1. 1. 1. 1. 1.]
 [1. 1. 1. 9. 1. 1. 1. 1.]
 [1. 1. 1. 1. 9. 1. 1. 1.]
 [1. 1. 1. 1. 1. 9. 1. 1.]
 [1. 1. 1. 1. 1. 1. 9. 1.]
 [1. 1. 1. 1. 1. 1. 1. 9.]]


In [58]:
#latihan 12

#mengubah dan mencetak matrik (c) dengan matrik (f), hanya pada urutan baris ke 1 dengan batas sebelum -1, dan kolom ke 1 dengan batas sebelum -1
c[1:-1,1:-1] = f
print(c)

[[9. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 9. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 9. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 9. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 9. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 9. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 9. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 9. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 9. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 9.]]


# 5.20.4 Copy pada Numpy
Kita sering kali menduplikat suatu variabel dengan maksud untuk mempercepat pekerjaan kita. Akan tetapi, sering tanpa disadari ikatan persamaan dalam Numpy sedemikian eratnya sehingga saat anggota variabel baru dirubah, dampaknya juga akan merubah variabel asal. Untuk menghindari perubahan variabel awal yang tidak dikehendaki maka diperlukan perintah copy seperti pada latihan berikut:

In [59]:
#latihan 1

#pertama-tama pikirkan dan buat numpy yang diinginkan
x = np.array([6,7,8,9,10])
#6 = urutan ke 0 atau -5
#7 = urutan ke 1 atau -4
#8 = urutan ke 2 atau -3
#9 = urutan ke 3 atau -2
#10 = urutan ke 4 atau -1

#mencetak numpy yang diinginkan
print(x)

[ 6  7  8  9 10]


In [60]:
#latihan 2

#cara meng'copy numpy dengan cara biasa
y = x
print(y)

[ 6  7  8  9 10]


In [61]:
#latihan 3

#untuk penjelasan urutan sama dengan latihan 1
#mengubah dan mencetak anggota numpy baru urutan ke 2 dengan "15"
y[2] = 15
print(y)

[ 6  7 15  9 10]


In [62]:
#latihan 4

#mencetak ulang numpy awal, tetapi anggotanya akan berubah sesuai dengan numpy baru karena menggunakan aturan copy biasa
print(x)

[ 6  7 15  9 10]


In [63]:
#latihan 5

#pertama-tama pikirkan dan buat numpy yang diinginkan
a = np.array([6,7,8,9,10])
#6 = urutan ke 0 atau -5
#7 = urutan ke 1 atau -4
#8 = urutan ke 2 atau -3
#9 = urutan ke 3 atau -2
#10 = urutan ke 4 atau -1

#mencetak numpy yang diinginkan
print(a)

[ 6  7  8  9 10]


In [64]:
#latihan 6

#dengan menggunakan aturan copy pada numpy
#mencetak numpy baru
b = a.copy()
print(b)

[ 6  7  8  9 10]


In [65]:
#latihan 7

#untuk penjelasan urutan sama dengan latihan 5
#mengubah dan mencetak anggota numpy baru urutan ke 2 dengan "15"
b[2] = 15
print(b)

[ 6  7 15  9 10]


In [66]:
#latihan 8

#mencetak ulang numpy awal, anggotanya akan sama dengan cetakan awal karena sudah menggunakan aturan copy pada numpy
print(a)

[ 6  7  8  9 10]


# 5.20.5 Operasi Matematika pada Numpy

In [69]:
#latihan 1

#numpy yang digunakan masih sama dengan numpy (x) pada latihan copy pada numpy
#operasi penjumlahan
#menjumlahkan dengan 2 dan mencetak ulang numpy(x)
x+2

array([ 8,  9, 17, 11, 12])

In [70]:
#latihan 2

#operasi pengurangan
#mengurangi dengan 3 dan mencetak ulang numpy (x)
x-3

array([ 3,  4, 12,  6,  7])

In [71]:
#latihan 3

#operasi perkalian
#mengalikan dengan 2 dan mencetak ulang numpy (x)
x*2

array([12, 14, 30, 18, 20])

In [72]:
#latihan 4

#operasi pembagian
#membagi dengan 2 dan mencetak ulang numpy (x)
x/2

array([3. , 3.5, 7.5, 4.5, 5. ])

In [73]:
#latihan 5

#operasi pemangkatan
#memangkatkan dengan 3 dan mencetak ulang numpy (x)
x**3

array([ 216,  343, 3375,  729, 1000], dtype=int32)

In [75]:
#latihan 6

#numpy yang digunakan masih sama dengan numpy (a) pada latihan copy pada numpy
#operasi dalam fungsi trigonometri
#menentukan nilai sin dari numpy (a)
np.sin(a)

array([-0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [77]:
#latihan 7

#operasi dalam fungsi trigonometri
#menentukan nilai cos dari numpy (a)
np.cos(a)

array([ 0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

In [78]:
#latihan 8

#operasi dalam fungsi trigonometri
#menentukan nilai tan dari numpy (a)
np.tan(a)

array([-0.29100619,  0.87144798, -6.79971146, -0.45231566,  0.64836083])

In [79]:
#latihan 9

#operasi dalam fungsi hiperbolik
#menentukan nilai sinh dari numpy (a)
np.sinh(a)

array([  201.71315737,   548.31612327,  1490.47882579,  4051.54190208,
       11013.2328747 ])

In [80]:
#latihan 10

#operasi dalam fungsi hiperbolik
#menentukan nilai cosh dari numpy (a)
np.cosh(a)

array([  201.71563612,   548.31703516,  1490.47916125,  4051.54202549,
       11013.2329201 ])

In [82]:
#latihan 11

#operasi dalam fungsi hiperbolik
#menentukan nilai tanh dari numpy (a)
np.tanh(a)

array([0.99998771, 0.99999834, 0.99999977, 0.99999997, 1.        ])

In [83]:
#latihan 12

#operasi akar
#menentukan akar kuadrat dari numpy (a)
np.sqrt(a)

array([2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

# 5.20.6 Perkalian Matrik pada Numpy
Operasi matematika pada suatu matrik dengan Numpy akan mengoperaikan elemen yang baris dan kolomnya sama. Tentunya hal ini akan memberikan hasil berbeda jika yang kita kehendaki adalah perkalian dua matrik. Perkalian matrik pada Numpy dapat menggunakan perintah matmul. Perlu dijadikan perhatian tentang ukuran matrik yang akan dikalikan harus sesuai dengan persyaratan. Misalnya matrik ukuran (2x3) dapat dikalikan dengan matrik ukuran (3x4).

In [84]:
#latihan 1

#membuat dan mencetak matrik berordo 2x4
a = np.array([[1,2,3,4], [5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [85]:
#latihan 2

#membuat dan mencetak matrik berodo 2x4 yang berbeda dengan latihan 1
b = np.array([[9,10,11,12], [13,14,15,16]])
print(b)

[[ 9 10 11 12]
 [13 14 15 16]]


In [86]:
#latihan 3

##mengalikan matrik (a) dan matrik (b)
c = a*b
print(c)
#dalam latihan ini, output akan muncul karena kedua matrik memiliki ordo yang sama

[[  9  20  33  48]
 [ 65  84 105 128]]


In [90]:
#latihan 4

#mengalikan matrik (a) dan matrik (b) dengan perintah matmul
d = np.matmul(a,b)
print(d)
#dalam latihan ini, output akan error, karena ordo kedua matrik tersebut tidak memenuhi syarat
#seharusnya jika matrik (a) berordo 2x4, maka matrik (b) harus berordo  4x2

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 4)

In [91]:
#latihan 5

#membuat dan mencetak matrik berordo 2x4
e = np.array([[9,10], [11,12], [13,14], [15,16]])
print(e)

[[ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [92]:
#latihan 6

#mengalikan matrik (a) dan matrik (e) dengan perintah matmul
f = np.matmul(a,e)
print(f)
#dalam latihan ini, outputnya akan muncul, karena ordo kedua matrik memenuhi syarat
#yaitu matrik (a) berordo 2x4, dan matrik (b) berordo (4x2)

[[130 140]
 [322 348]]


In [93]:
#latihan 7

#mengalikan matrik (a) dan matrik (e) tanpa menggunakan perintah matmul
g = a*e
#dalam latihan ini, output akan error, karena kedua matrik tersebut memiliki ordo yang berbeda
#yaitu matrik (a) berordo 2x4, dan matrik (b) berordo (4x2)

ValueError: operands could not be broadcast together with shapes (2,4) (4,2) 

# 5.20.7 min, max dan sum pada Numpy
min = minimum
max = maksimum
sum = pemjumlahan

In [94]:
#latihan 1

#membuat dan mencetak matrik yang diinginkan
a = np.array([[1,2,3,4],
              [5,6,7,8],
              [9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [96]:
#latihan 2

#menentukan dan mencetak nilai minimum dari anggota matrik (a)
b = np.min(a)
print(b)

1


In [103]:
#latihan 3

#menentukan dan mencetak nilai minimum tiap kolom dari matrik (a)
c = np.min(a,axis=0)
print(c)

[1 2 3 4]


In [105]:
#latihan 4

#menentukan dan mencetak nilai minimun tiap baris dari matrik (a)
d = np.min(a,axis=1)
print(d)

[1 5 9]


In [106]:
#latihan 5

#menentukan dan mencetak nilai maksimum dari anggota matrik (a)
e = np.max(a)
print(e)

12


In [107]:
#latihan 6

#menentukan dan mencetak nilai maksimum tiap kolom dari matrik (a)
f = np.max(a,axis=0)
print(f)

[ 9 10 11 12]


In [108]:
#latihan 7

#menentukan dan mencetak nilai maksimum tiap baris dari matrik (a)
g = np.max(a,axis=1)
print(g)

[ 4  8 12]


In [109]:
#latihan 8

#menjumlahkan dan mencetak matrik (a)
h = np.sum(a)
print(a)
#karena tidak ada matrik lain yang ditambahkan, maka outputnya akan sama dengan matrik (a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [110]:
#latihan 9

#menjumlahkan dan mencetak tiap kolom dari matrik (a)
i = np.sum(a,axis=0)
print(i)

[15 18 21 24]


In [111]:
#latihan 10

#menjumlahkan dan mencetak tiap baris dari matrik (a)
j = np.sum(a,axis=1)
print(j)

[10 26 42]
